INSERT INTO `aspects`( `name`, `description`) VALUES ('Beauty','Reflects how visually appealing and attractive a place is.'), ('Sound', 'Refers to the pleasantness of noises in a certain place.'), 
('Movement', 'Shows how easy and convenient it is to move around an area, whether you are walking, cycling, or using a wheelchair.'), 
('Protection', 'Indicates how safe and protected a place is from traffic and other urban hazards.'), 
('Climate comfort', 'Reflects how comfortable the climate feels in an area, considering heat, rain cover, wind shelter and more.'),
('Activities', 'Represent the usability of a place for the citizens.'),
("Architecture & sights", ""),
('Buildings',  '' ),
            ('Landmarks',  ""),
            ('Colours',  '' ),
            ('Street Art',  '' ),
            ('Nature',  '' ),
            ('Trees',  '' ),
            ('Plants',  '' ),
            ('Gardens',  '' ),
            ('Water',  ''),
            ('Care',  ''),
            ('Cleanliness',  '' ),
            ('Smell',  ''),

            ('Water',  '' ),
            ('Wind',  ''),
            ('Animals',  '' ),
            
            ('Human sounds',  '' ),
            ('Voices',  '' ),
            ('Crowds',  '' ),
            ('Children',  ''),
            ('City noises',  '' ),
            ('Music',  ''),
            ('Traffic',  ''),
            ('Construction',  ''),

			('Accessibility',  ''),
            ('Walking', ''),
            ('Cycling',  '' ),
            ('Wheelchair access',  ''),
            ('Comfort',  ''),
            ('Benches',  '' ),
            ('Stairs',  ''),
            ('Sidewalks',  ''),
            ('Connectivity',  ''),
            ('Crosswalks',  ''),
            ('Public transport',  ''),
            ('Wayfinding',  ''),

			('Protection from traffic',  ''),
            ('Cars',  ''),
            ('Visibility',  ''),
            ('Traffic signs',  '' ),
            ('People safety',  '' ),
            ('Children safety', ''),
            ('Animal safety',  ''),
            ('Lighting',  ''),
            
            ('Quality of roads & buildings',  ''),
            ('Pavement quality',  '' ),
            ('Road condition',  '' ),
            ('Building condition',  ''),

			('Weather',  ''),
            ('Heat',  ''),
            ('Humidity',  ''),
            ('Airflow',  '' ),
            
            ('Climate protection',  '' ),
            ('Shade',  ''),
            ('Rain cover',  ''),
            ('Wind shelter',  ''),

			('Everyday activities', ''),
            ('Sports',  ''),
            ('Shopping',  ''),
            ('Food',  ''),
            
            ('Social activities', ''),
            ('Dog parks', ''),
            ('Playground',  ''),
            ('Relaxation',  ''),
            ('Friends meetup', ''),
            ('Coffee',  ''),
            
            ('Essential needs', ''),
            ('Toilet', '' ),
            ('Drinking water', '');