INSERT INTO `project_team` (`id`, `project_id`, `team_id`, `role`, `created_at`, `updated_at`) 
VALUES (NULL, '15', '1', 'research lead', NULL, NULL), 
(NULL, '15', '3', 'advisor', NULL, NULL),
(NULL, '15', '4', 'researcher', NULL, NULL), 
(NULL, '15', '5', 'technical implementation', NULL, NULL),
(NULL, '15', '9', 'researcher', NULL, NULL), 
(NULL, '15', '10', 'research assistant', NULL, NULL),
(NULL, '14', '1', 'research lead', NULL, NULL), 
(NULL, '14', '3', 'technical implementation lead', NULL, NULL),
(NULL, '14', '4', 'researcher', NULL, NULL), 
(NULL, '14', '5', 'technical implementation', NULL, NULL),
(NULL, '14', '6', 'UI / UX', NULL, NULL),
(NULL, '14', '8', 'researcher', NULL, NULL), 
(NULL, '14', '9', 'researcher', NULL, NULL), 
(NULL, '14', '10', 'research assistant', NULL, NULL),
(NULL, '16', '1', 'project lead', NULL, NULL), 
(NULL, '16', '10', 'research assistant', NULL, NULL),
(NULL, '16', '11', 'external collaborator', NULL, NULL), 

(NULL, '17', '1', 'project lead', NULL, NULL), 
(NULL, '17', '3', 'technical implementation lead', NULL, NULL),
(NULL, '17', '4', 'researcher', NULL, NULL), 
(NULL, '17', '8', 'researcher', NULL, NULL), 
(NULL, '18', '1', 'project lead', NULL, NULL), 
(NULL, '18', '3', 'technical implementation lead', NULL, NULL),
(NULL, '18', '4', 'researcher', NULL, NULL), 
(NULL, '18', '12', 'technical implementation', NULL, NULL);